import fs from 'fs';
import path from 'path';

// Definition of 114 additional realistic marketplace products (IDs 51 to 164)
export const newProducts = [
  // --- ELECTRONICS (27 products: 51 to 77) ---
  {
    product_id: 51,
    vendor_id: 11,
    product_name: 'Wireless ANC Headphones',
    description: 'Active noise cancelling over-ear headphones with 40-hour battery life and fast USB-C charging.',
    price: 4999.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.8,
    review_count: 185,
    brand: 'Audio World',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    stock: 25,
  },
  {
    product_id: 52,
    vendor_id: 48,
    product_name: 'AMOLED Smartwatch',
    description: '1.43-inch high-resolution AMOLED display with Bluetooth calling, heart rate, and SpO2 tracking.',
    price: 3499.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.6,
    review_count: 142,
    brand: 'Gadget Hub',
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
    stock: 40,
  },
  {
    product_id: 53,
    vendor_id: 1,
    product_name: 'KeyCraft RGB Mechanical Keyboard',
    description: 'Hot-swappable mechanical switches with customizable per-key RGB backlighting and braided cable.',
    price: 3999.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.9,
    review_count: 210,
    brand: 'Tech World',
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    stock: 18,
  },
  {
    product_id: 54,
    vendor_id: 43,
    product_name: 'SwiftGlide Ergonomic Wireless Mouse',
    description: '2.4GHz and Bluetooth dual-mode wireless mouse with silent clicks and contoured thumb rest.',
    price: 1299.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.5,
    review_count: 98,
    brand: 'Tech Hub',
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
    stock: 50,
  },
  {
    product_id: 55,
    vendor_id: 21,
    product_name: '7-in-1 USB-C Docking Station',
    description: 'Multiport hub with 4K HDMI, 100W Power Delivery, SD/TF card readers, and 3 high-speed USB 3.0 ports.',
    price: 2499.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.7,
    review_count: 130,
    brand: 'Electro Mart',
    imageUrl: 'https://images.unsplash.com/photo-1625842268584-8f3296236761?w=800&auto=format&fit=crop&q=80',
    stock: 35,
  },
  {
    product_id: 56,
    vendor_id: 48,
    product_name: '20000mAh 65W Fast Power Bank',
    description: 'High-capacity power bank capable of laptop and mobile fast charging with smart digital LED percentage display.',
    price: 2199.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.8,
    review_count: 310,
    brand: 'Gadget Hub',
    imageUrl: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=800&auto=format&fit=crop&q=80',
    stock: 75,
  },
  {
    product_id: 57,
    vendor_id: 6,
    product_name: '4K Ultra HD Streaming Webcam',
    description: '4K 30fps streaming camera with dual stereo noise-cancelling microphones and physical privacy shutter.',
    price: 3299.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.6,
    review_count: 84,
    brand: 'Mobile Planet',
    imageUrl: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?w=800&auto=format&fit=crop&q=80',
    stock: 20,
  },
  {
    product_id: 58,
    vendor_id: 45,
    product_name: 'High-Precision Gaming Mouse',
    description: '16,000 DPI optical sensor with programmable macro buttons, PTFE glide feet, and RGB lighting zones.',
    price: 1799.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.7,
    review_count: 175,
    brand: 'Gaming World',
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80',
    stock: 30,
  },
  {
    product_id: 59,
    vendor_id: 8,
    product_name: '1TB Portable External SSD',
    description: 'Ultra-compact rugged solid-state drive with up to 1050MB/s read speeds and USB 3.2 Gen 2 connectivity.',
    price: 6499.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.9,
    review_count: 160,
    brand: 'Laptop House',
    imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80',
    stock: 15,
  },
  {
    product_id: 60,
    vendor_id: 1,
    product_name: '128GB High-Speed USB 3.2 Flash Drive',
    description: 'Metallic unibody pendrive with transfer speeds up to 150MB/s for reliable file storage and backup.',
    price: 799.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.5,
    review_count: 290,
    brand: 'Tech World',
    imageUrl: 'https://images.unsplash.com/photo-1618410320928-25228d811631?w=800&auto=format&fit=crop&q=80',
    stock: 120,
  },
  {
    product_id: 61,
    vendor_id: 30,
    product_name: 'Ergonomic Aluminum Laptop Stand',
    description: 'Ventilated foldable aluminum riser supporting laptops up to 17 inches for improved posture and airflow.',
    price: 1499.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.8,
    review_count: 220,
    brand: 'Computer Zone',
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
    stock: 45,
  },
  {
    product_id: 62,
    vendor_id: 8,
    product_name: '24-Inch IPS Frameless FHD Monitor',
    description: '100Hz refresh rate IPS display with 99% sRGB color gamut, ultra-thin bezels, and eye-care low blue light mode.',
    price: 8999.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.7,
    review_count: 110,
    brand: 'Laptop House',
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
    stock: 12,
  },
  {
    product_id: 63,
    vendor_id: 43,
    product_name: 'Wi-Fi 6 Dual-Band Gigabit Router',
    description: 'Next-gen AX1800 Wi-Fi 6 router with 4 high-gain antennas and beamforming technology for seamless coverage.',
    price: 2899.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.6,
    review_count: 95,
    brand: 'Tech Hub',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    stock: 25,
  },
  {
    product_id: 64,
    vendor_id: 50,
    product_name: '120W Dolby Cinematic Soundbar',
    description: '2.1 channel soundbar with dedicated wired subwoofer, optical, HDMI ARC, and Bluetooth connectivity.',
    price: 7499.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.7,
    review_count: 140,
    brand: 'Super Deals',
    imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
    stock: 10,
  },
  {
    product_id: 65,
    vendor_id: 32,
    product_name: 'Smart LED RGB Smart Bulb (2-Pack)',
    description: '9W 16-million color Wi-Fi smart bulbs compatible with voice assistants and customizable lighting schedules.',
    price: 899.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.4,
    review_count: 180,
    brand: 'Smart Home',
    imageUrl: 'https://images.unsplash.com/photo-1550524514-6f0a4f5f543f?w=800&auto=format&fit=crop&q=80',
    stock: 80,
  },
  {
    product_id: 66,
    vendor_id: 21,
    product_name: '1080p Home Cinema Mini Projector',
    description: 'Portable multimedia projector with 4500 lumens brightness, built-in speaker, and screen mirroring support.',
    price: 12499.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.5,
    review_count: 65,
    brand: 'Electro Mart',
    imageUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=800&auto=format&fit=crop&q=80',
    stock: 8,
  },
  {
    product_id: 67,
    vendor_id: 25,
    product_name: 'Fitness Smart Band with SpO2',
    description: 'Lightweight fitness tracker with continuous heart rate monitoring, 30+ sports modes, and 14-day battery life.',
    price: 1999.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.6,
    review_count: 240,
    brand: 'Fitness World',
    imageUrl: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&auto=format&fit=crop&q=80',
    stock: 60,
  },
  {
    product_id: 68,
    vendor_id: 43,
    product_name: 'Braided 4K 60Hz HDMI 2.1 Cable',
    description: '2-meter gold-plated high-speed HDMI cable supporting 48Gbps bandwidth, eARC, and HDR10+ video.',
    price: 499.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.8,
    review_count: 320,
    brand: 'Tech Hub',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    stock: 150,
  },
  {
    product_id: 69,
    vendor_id: 11,
    product_name: 'Studio USB Condenser Microphone',
    description: 'Cardioid polar pattern studio microphone with desktop shock mount, pop filter, and zero-latency headphone jack.',
    price: 3999.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.7,
    review_count: 115,
    brand: 'Audio World',
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    stock: 22,
  },
  {
    product_id: 70,
    vendor_id: 42,
    product_name: '4-Outlet Surge Protector Power Strip',
    description: 'Heavy-duty 2-meter extension cord with 4 universal AC sockets, 3 smart USB ports, and surge suppression.',
    price: 999.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.7,
    review_count: 190,
    brand: 'Daily Needs',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    stock: 65,
  },
  {
    product_id: 71,
    vendor_id: 11,
    product_name: '2.1 Channel Bluetooth Computer Speakers',
    description: 'Desktop stereo speaker system with front-facing wooden subwoofer and accessible volume control pod.',
    price: 2699.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.5,
    review_count: 85,
    brand: 'Audio World',
    imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop&q=80',
    stock: 18,
  },
  {
    product_id: 72,
    vendor_id: 12,
    product_name: 'Digital Graphics Drawing Tablet',
    description: '10x6 inch active drawing area with 8192 levels of battery-free pressure sensitivity and 8 shortcut keys.',
    price: 4499.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.8,
    review_count: 92,
    brand: 'Gaming Arena',
    imageUrl: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&auto=format&fit=crop&q=80',
    stock: 14,
  },
  {
    product_id: 73,
    vendor_id: 1,
    product_name: '2TB Rugged External Hard Drive',
    description: 'Shock-resistant portable hard disk drive formatted for Windows and Mac with automatic backup software.',
    price: 5299.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.6,
    review_count: 140,
    brand: 'Tech World',
    imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80',
    stock: 30,
  },
  {
    product_id: 74,
    vendor_id: 38,
    product_name: 'Padded Waterproof Laptop Backpack',
    description: '15.6-inch laptop bag with dedicated tablet sleeve, anti-theft hidden pocket, and USB charging pass-through.',
    price: 1899.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.7,
    review_count: 165,
    brand: 'Travel World',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
    stock: 45,
  },
  {
    product_id: 75,
    vendor_id: 30,
    product_name: 'Dual-Fan RGB Laptop Cooling Pad',
    description: 'High-airflow aerodynamic cooling pad with 6 adjustable height angles and dual USB passthrough ports.',
    price: 1299.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.4,
    review_count: 88,
    brand: 'Computer Zone',
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
    stock: 35,
  },
  {
    product_id: 76,
    vendor_id: 26,
    product_name: 'Bluetooth Overhead Mobile Tripod',
    description: 'Expandable 54-inch phone tripod stand with 360-degree rotation and detachable wireless shutter remote.',
    price: 899.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.5,
    review_count: 120,
    brand: 'Camera House',
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
    stock: 55,
  },
  {
    product_id: 77,
    vendor_id: 20,
    product_name: '10-Inch Dimmable LED Ring Light',
    description: '3 color temperature modes and 10 brightness levels with sturdy metal desktop tripod stand for video calls.',
    price: 1199.00,
    category: 'Electronics',
    product_status: 'Active',
    rating: 4.6,
    review_count: 140,
    brand: 'Daily Deals',
    imageUrl: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?w=800&auto=format&fit=crop&q=80',
    stock: 40,
  },

  // --- FASHION (23 products: 78 to 100) ---
  {
    product_id: 78,
    vendor_id: 2,
    product_name: 'Classic Oxford Button-Down Shirt',
    description: '100% breathable combed cotton Oxford shirt with tailored regular fit and button-down collar.',
    price: 1499.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.6,
    review_count: 110,
    brand: 'Fashion Hub',
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80',
    stock: 30,
  },
  {
    product_id: 79,
    vendor_id: 22,
    product_name: 'Pure Linen Casual Summer Shirt',
    description: 'Pre-washed lightweight European linen shirt designed for casual comfort in warm tropical climates.',
    price: 1799.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.7,
    review_count: 85,
    brand: 'Urban Wear',
    imageUrl: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80',
    stock: 25,
  },
  {
    product_id: 80,
    vendor_id: 7,
    product_name: 'Premium Pima Cotton Polo T-Shirt',
    description: 'Silk-soft extra-long staple cotton polo with rib-knit collar and mother-of-pearl buttons.',
    price: 1199.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.5,
    review_count: 130,
    brand: 'Style Street',
    imageUrl: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop&q=80',
    stock: 40,
  },
  {
    product_id: 81,
    vendor_id: 31,
    product_name: 'Heavyweight Oversized Graphic Tee',
    description: '240 GSM dense cotton drop-shoulder streetwear t-shirt with high-density minimalist chest print.',
    price: 899.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.8,
    review_count: 195,
    brand: 'Fashion Point',
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
    stock: 60,
  },
  {
    product_id: 82,
    vendor_id: 22,
    product_name: 'Fleece Lined Winter Pullover Hoodie',
    description: '320 GSM brushed fleece hoodie featuring double-layered hood and kangaroo pocket for winter warmth.',
    price: 2299.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.7,
    review_count: 160,
    brand: 'Urban Wear',
    imageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
    stock: 28,
  },
  {
    product_id: 83,
    vendor_id: 2,
    product_name: 'French Terry Crewneck Sweatshirt',
    description: 'Classic loopback cotton knit crewneck with ribbed cuffs and hem for easy layering.',
    price: 1699.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.5,
    review_count: 90,
    brand: 'Fashion Hub',
    imageUrl: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&auto=format&fit=crop&q=80',
    stock: 35,
  },
  {
    product_id: 84,
    vendor_id: 7,
    product_name: 'Slim Fit Stretch Denim Jeans',
    description: 'Mid-rise indigo denim with 2% elastane for flexible mobility and authentic whiskered vintage wash.',
    price: 2199.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.6,
    review_count: 140,
    brand: 'Style Street',
    imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80',
    stock: 45,
  },
  {
    product_id: 85,
    vendor_id: 44,
    product_name: 'Relaxed Fit Cotton Chinos',
    description: 'Breathable twill cotton trousers with flat-front tailoring suitable for smart casual and office wear.',
    price: 1799.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.5,
    review_count: 105,
    brand: 'Style Hub',
    imageUrl: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&auto=format&fit=crop&q=80',
    stock: 30,
  },
  {
    product_id: 86,
    vendor_id: 31,
    product_name: '6-Pocket Tactical Cargo Pants',
    description: 'Durable ripstop cotton cargo pants with reinforced knees, deep utility pockets, and drawstring cuffs.',
    price: 1999.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.6,
    review_count: 125,
    brand: 'Fashion Point',
    imageUrl: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?w=800&auto=format&fit=crop&q=80',
    stock: 25,
  },
  {
    product_id: 87,
    vendor_id: 22,
    product_name: 'Italian Cut Formal Trousers',
    description: 'Poly-viscose wrinkle-resistant formal pants with internal shirt-grip waistband and tapered silhouette.',
    price: 1899.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.7,
    review_count: 95,
    brand: 'Urban Wear',
    imageUrl: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&auto=format&fit=crop&q=80',
    stock: 35,
  },
  {
    product_id: 88,
    vendor_id: 4,
    product_name: 'Tapered Athletic Joggers',
    description: 'Moisture-wicking French terry athletic track joggers with zippered side pockets and elasticated cuffs.',
    price: 1299.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.5,
    review_count: 150,
    brand: 'Sports Zone',
    imageUrl: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=800&auto=format&fit=crop&q=80',
    stock: 50,
  },
  {
    product_id: 89,
    vendor_id: 33,
    product_name: 'Breathable Running Track Pants',
    description: 'Quick-drying lightweight polyester sports pants with ankle zippers and reflective safety strips.',
    price: 999.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.4,
    review_count: 110,
    brand: 'Sports House',
    imageUrl: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&auto=format&fit=crop&q=80',
    stock: 40,
  },
  {
    product_id: 90,
    vendor_id: 22,
    product_name: 'Minimalist White Leather Sneakers',
    description: 'Clean profile vegan leather low-top sneakers with vulcanized rubber sole and cushioned insoles.',
    price: 2799.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.8,
    review_count: 230,
    brand: 'Urban Wear',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
    stock: 35,
  },
  {
    product_id: 91,
    vendor_id: 4,
    product_name: 'Cushioned Mesh Road Running Shoes',
    description: 'Responsive EVA midsole athletic shoes with breathable engineered mesh upper and anti-skid grip.',
    price: 3299.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.7,
    review_count: 175,
    brand: 'Sports Zone',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
    stock: 25,
  },
  {
    product_id: 92,
    vendor_id: 2,
    product_name: 'Handcrafted Tan Penny Loafers',
    description: 'Full-grain leather slip-on loafers with cushioned memory footbed and durable stacked heel.',
    price: 2999.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.6,
    review_count: 85,
    brand: 'Fashion Hub',
    imageUrl: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&auto=format&fit=crop&q=80',
    stock: 18,
  },
  {
    product_id: 93,
    vendor_id: 44,
    product_name: 'Genuine Leather Reversible Formal Belt',
    description: 'Dual-sided black and brown leather belt with rotatable brushed steel alloy prong buckle.',
    price: 899.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.5,
    review_count: 140,
    brand: 'Style Hub',
    imageUrl: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=800&auto=format&fit=crop&q=80',
    stock: 60,
  },
  {
    product_id: 94,
    vendor_id: 7,
    product_name: 'Full-Grain Leather Bi-Fold Wallet',
    description: 'Slimline RFID-blocking genuine leather wallet with 8 card slots and dual currency compartments.',
    price: 1099.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.8,
    review_count: 210,
    brand: 'Style Street',
    imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80',
    stock: 50,
  },
  {
    product_id: 95,
    vendor_id: 31,
    product_name: 'UV400 Polarized Aviator Sunglasses',
    description: 'Classic teardrop metallic frame sunglasses with glare-reducing polarized lenses and silicone nose pads.',
    price: 1499.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.6,
    review_count: 165,
    brand: 'Fashion Point',
    imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80',
    stock: 40,
  },
  {
    product_id: 96,
    vendor_id: 2,
    product_name: 'Embroidered Silk Blend Festive Kurta',
    description: 'Jacquard woven mandarin collar kurta with intricate thread embroidery and side slits for celebrations.',
    price: 2499.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.7,
    review_count: 90,
    brand: 'Fashion Hub',
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80',
    stock: 22,
  },
  {
    product_id: 97,
    vendor_id: 44,
    product_name: 'Traditional Cotton Anarkali Dress',
    description: 'Flared pure cotton printed ethnic gown with hand block prints and matching dupatta.',
    price: 2899.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.8,
    review_count: 115,
    brand: 'Style Hub',
    imageUrl: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop&q=80',
    stock: 18,
  },
  {
    product_id: 98,
    vendor_id: 31,
    product_name: 'Premium Vegan Leather Tote Handbag',
    description: 'Spacious structured shoulder tote with central zippered organizer pocket and detachable strap.',
    price: 2499.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.6,
    review_count: 130,
    brand: 'Fashion Point',
    imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80',
    stock: 25,
  },
  {
    product_id: 99,
    vendor_id: 7,
    product_name: 'Vintage Washed Denim Trucker Jacket',
    description: 'Rugged 14oz cotton denim outerwear with shank buttons, chest flap pockets, and adjustable waist tabs.',
    price: 3199.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.8,
    review_count: 145,
    brand: 'Style Street',
    imageUrl: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&auto=format&fit=crop&q=80',
    stock: 20,
  },
  {
    product_id: 100,
    vendor_id: 4,
    product_name: 'Structured Cotton Baseball Cap',
    description: '6-panel twill athletic cap with pre-curved visor and adjustable metal buckle backstrap.',
    price: 599.00,
    category: 'Fashion',
    product_status: 'Active',
    rating: 4.5,
    review_count: 180,
    brand: 'Sports Zone',
    imageUrl: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&auto=format&fit=crop&q=80',
    stock: 75,
  },

  // --- HOME & LIVING (23 products: 101 to 123) ---
  {
    product_id: 101,
    vendor_id: 24,
    product_name: 'Modern Nordic Minimalist Table Lamp',
    description: 'Solid wood base bedside lamp with warm white fabric drum shade and inline switch.',
    price: 1699.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.8,
    review_count: 110,
    brand: 'Home Decor',
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80',
    stock: 25,
  },
  {
    product_id: 102,
    vendor_id: 24,
    product_name: 'Adjustable Arc Floor Lamp with Shade',
    description: 'Matte black arched standing lamp with weighted base and 360-degree pivoting lampshade.',
    price: 3499.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.7,
    review_count: 75,
    brand: 'Home Decor',
    imageUrl: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&auto=format&fit=crop&q=80',
    stock: 12,
  },
  {
    product_id: 103,
    vendor_id: 20,
    product_name: 'Touch-Controlled LED Desk Lamp',
    description: '5 brightness levels, 3 color modes, and integrated 5V USB output for smartphone charging.',
    price: 1299.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.6,
    review_count: 140,
    brand: 'Daily Deals',
    imageUrl: 'https://images.unsplash.com/photo-1534353436294-0dbd4bdac845?w=800&auto=format&fit=crop&q=80',
    stock: 35,
  },
  {
    product_id: 104,
    vendor_id: 24,
    product_name: '400 TC Pure Sateen Cotton Bedsheet Set',
    description: 'Silky smooth king size bedsheet with two matching pillow covers crafted from long-staple cotton.',
    price: 1899.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.8,
    review_count: 220,
    brand: 'Home Decor',
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&auto=format&fit=crop&q=80',
    stock: 45,
  },
  {
    product_id: 105,
    vendor_id: 42,
    product_name: 'Memory Foam Ergonomic Sleeping Pillow',
    description: 'Contoured orthopedic neck support pillow with breathable removable bamboo fabric cover.',
    price: 1199.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.6,
    review_count: 165,
    brand: 'Daily Needs',
    imageUrl: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&auto=format&fit=crop&q=80',
    stock: 40,
  },
  {
    product_id: 106,
    vendor_id: 24,
    product_name: 'Geometric Embroidered Cushion Covers (Set of 5)',
    description: '16x16 inch decorative cotton canvas cushion cases with hidden zipper closures.',
    price: 899.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.7,
    review_count: 130,
    brand: 'Home Decor',
    imageUrl: 'https://images.unsplash.com/photo-1579656381226-5fc0f0100c3b?w=800&auto=format&fit=crop&q=80',
    stock: 55,
  },
  {
    product_id: 107,
    vendor_id: 20,
    product_name: 'Ultra-Soft Microfiber Reversible Blanket',
    description: 'Lightweight all-season double bed comforter with anti-microbial hypoallergenic microfibre filling.',
    price: 1999.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.8,
    review_count: 185,
    brand: 'Daily Deals',
    imageUrl: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&auto=format&fit=crop&q=80',
    stock: 30,
  },
  {
    product_id: 108,
    vendor_id: 24,
    product_name: 'Thermal Insulated Blackout Window Curtains',
    description: 'Pair of 7-foot eyelet curtains blocking 95% sunlight and reducing external room noise.',
    price: 1499.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.6,
    review_count: 95,
    brand: 'Home Decor',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
    stock: 25,
  },
  {
    product_id: 109,
    vendor_id: 14,
    product_name: '4-Tier Multipurpose Storage Organizer',
    description: 'Heavy-duty rolling utility cart with caster wheels suitable for kitchen, bathroom, or study room.',
    price: 1599.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.7,
    review_count: 140,
    brand: 'Kitchen Mart',
    imageUrl: 'https://images.unsplash.com/photo-1591129841117-3adfd313e34f?w=800&auto=format&fit=crop&q=80',
    stock: 35,
  },
  {
    product_id: 110,
    vendor_id: 35,
    product_name: 'Engineered Wood 3-Tier Shoe Rack',
    description: 'Space-saving compact hallway organizer accommodating up to 12 pairs of footwear.',
    price: 2299.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.5,
    review_count: 80,
    brand: 'Furniture World',
    imageUrl: 'https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=800&auto=format&fit=crop&q=80',
    stock: 18,
  },
  {
    product_id: 111,
    vendor_id: 35,
    product_name: 'Contemporary Ladder Bookshelf',
    description: '5-shelf leaning display shelving unit constructed from durable moisture-resistant board.',
    price: 3899.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.8,
    review_count: 90,
    brand: 'Furniture World',
    imageUrl: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&auto=format&fit=crop&q=80',
    stock: 15,
  },
  {
    product_id: 112,
    vendor_id: 35,
    product_name: 'Solid Wood Minimalist Study Table',
    description: 'Spacious work-from-home desk with scratch-resistant melamine finish and cable management hole.',
    price: 5999.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.7,
    review_count: 65,
    brand: 'Furniture World',
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&auto=format&fit=crop&q=80',
    stock: 10,
  },
  {
    product_id: 113,
    vendor_id: 19,
    product_name: 'Ergonomic High-Back Mesh Office Chair',
    description: 'Breathable mesh backrest chair with adjustable lumbar support, 2D armrests, and tilt lock.',
    price: 7499.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.8,
    review_count: 120,
    brand: 'Office Needs',
    imageUrl: 'https://images.unsplash.com/photo-1580481077197-0f8cf8dfbf45?w=800&auto=format&fit=crop&q=80',
    stock: 14,
  },
  {
    product_id: 114,
    vendor_id: 14,
    product_name: '1L Vacuum Insulated Steel Water Bottle',
    description: 'Food-grade 18/8 stainless steel bottle keeping beverages cold for 24 hours or hot for 12 hours.',
    price: 799.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.7,
    review_count: 240,
    brand: 'Kitchen Mart',
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=80',
    stock: 90,
  },
  {
    product_id: 115,
    vendor_id: 36,
    product_name: 'Handcrafted Ceramic Coffee Mugs (Set of 4)',
    description: '350ml microwave and dishwasher safe artisan pottery mugs with comfortable ergonomic handles.',
    price: 699.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.8,
    review_count: 170,
    brand: 'Kitchen World',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    stock: 50,
  },
  {
    product_id: 116,
    vendor_id: 14,
    product_name: '24-Piece Opalware Luxury Dinner Set',
    description: 'Chip-resistant, bone-ash free microwaveable complete dining collection for 6 persons.',
    price: 3299.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.9,
    review_count: 85,
    brand: 'Kitchen Mart',
    imageUrl: 'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?w=800&auto=format&fit=crop&q=80',
    stock: 15,
  },
  {
    product_id: 117,
    vendor_id: 36,
    product_name: 'Cast Iron Pre-Seasoned 10-Inch Skillet',
    description: 'Heavy-gauge natural non-stick frying pan for superior heat retention, searing, and oven baking.',
    price: 1599.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.8,
    review_count: 195,
    brand: 'Kitchen World',
    imageUrl: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=800&auto=format&fit=crop&q=80',
    stock: 35,
  },
  {
    product_id: 118,
    vendor_id: 14,
    product_name: '3-Piece Granite Non-Stick Cookware Set',
    description: 'PFOA-free kadai, fry pan, and flat tawa with cool-touch bakelite handles and induction base.',
    price: 2899.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.7,
    review_count: 140,
    brand: 'Kitchen Mart',
    imageUrl: 'https://images.unsplash.com/photo-1584990347449-30dfb0bfa442?w=800&auto=format&fit=crop&q=80',
    stock: 20,
  },
  {
    product_id: 119,
    vendor_id: 36,
    product_name: 'Stainless Steel Wall Mounted Spice Rack',
    description: 'Rust-proof 2-tier wire seasoning jar organizer with knife holder and utility hooks.',
    price: 899.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.5,
    review_count: 115,
    brand: 'Kitchen World',
    imageUrl: 'https://images.unsplash.com/photo-1584990347449-30dfb0bfa442?w=800&auto=format&fit=crop&q=80',
    stock: 40,
  },
  {
    product_id: 120,
    vendor_id: 24,
    product_name: 'Silent Sweep Minimalist Wall Clock',
    description: '12-inch non-ticking quartz wall clock with large easy-to-read numerals and glass cover.',
    price: 999.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.6,
    review_count: 130,
    brand: 'Home Decor',
    imageUrl: 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=800&auto=format&fit=crop&q=80',
    stock: 45,
  },
  {
    product_id: 121,
    vendor_id: 14,
    product_name: '1.8L Fast Boiling Electric Kettle',
    description: '1500W stainless steel rapid boil kettle with automatic shut-off and boil-dry protection.',
    price: 1199.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.7,
    review_count: 210,
    brand: 'Kitchen Mart',
    imageUrl: 'https://images.unsplash.com/photo-1594213114663-ddfe1e6a2bb0?w=800&auto=format&fit=crop&q=80',
    stock: 60,
  },
  {
    product_id: 122,
    vendor_id: 32,
    product_name: 'Hepa Filter Compact Room Air Purifier',
    description: 'True HEPA 3-stage filtration capturing 99.97% of airborne dust, smoke, pollen, and pet dander.',
    price: 6999.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.8,
    review_count: 85,
    brand: 'Smart Home',
    imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80',
    stock: 12,
  },
  {
    product_id: 123,
    vendor_id: 42,
    product_name: 'Premium Turkish Cotton Bath Towels (Pack of 2)',
    description: '600 GSM thick plush bath sheets with high water absorbency and double-stitched borders.',
    price: 1299.00,
    category: 'Home',
    product_status: 'Active',
    rating: 4.7,
    review_count: 155,
    brand: 'Daily Needs',
    imageUrl: 'https://images.unsplash.com/photo-1616627547584-bf28cee262db?w=800&auto=format&fit=crop&q=80',
    stock: 50,
  },

  // --- SPORTS & FITNESS (18 products: 124 to 141) ---
  {
    product_id: 124,
    vendor_id: 4,
    product_name: 'English Willow Professional Cricket Bat',
    description: 'Grade 1 hand-crafted English willow cricket bat with thick power edges and balanced pick-up.',
    price: 7499.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.9,
    review_count: 140,
    brand: 'Sports Zone',
    imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&auto=format&fit=crop&q=80',
    stock: 15,
  },
  {
    product_id: 125,
    vendor_id: 4,
    product_name: 'Red Leather Cricket Match Balls (Pack of 4)',
    description: 'Hand-stitched 4-piece alum tanned alum hide balls for club tournament play.',
    price: 999.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.6,
    review_count: 95,
    brand: 'Sports Zone',
    imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&auto=format&fit=crop&q=80',
    stock: 50,
  },
  {
    product_id: 126,
    vendor_id: 33,
    product_name: 'Premium Padded Cricket Batting Gloves',
    description: 'Multi-section high-density foam fingers with soft sheep leather palm for shock absorption.',
    price: 1299.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.7,
    review_count: 85,
    brand: 'Sports House',
    imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    stock: 35,
  },
  {
    product_id: 127,
    vendor_id: 4,
    product_name: 'High-Impact Cricket Batting Helmet',
    description: 'Lightweight ABS shell protective helmet with adjustable steel visor and sweat-wicking padding.',
    price: 2199.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.8,
    review_count: 70,
    brand: 'Sports Zone',
    imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&auto=format&fit=crop&q=80',
    stock: 20,
  },
  {
    product_id: 128,
    vendor_id: 33,
    product_name: 'Lightweight Polycarbonate Cricket Leg Pads',
    description: 'Ergonomically shaped batting pads with triple vertical bolsters and padded ankle protection.',
    price: 2499.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.7,
    review_count: 65,
    brand: 'Sports House',
    imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&auto=format&fit=crop&q=80',
    stock: 18,
  },
  {
    product_id: 129,
    vendor_id: 4,
    product_name: 'FIFA Standard Thermal Bonded Football',
    description: 'Seamless polyurethane outer surface match ball providing true trajectory and low water intake.',
    price: 1499.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.8,
    review_count: 190,
    brand: 'Sports Zone',
    imageUrl: 'https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?w=800&auto=format&fit=crop&q=80',
    stock: 45,
  },
  {
    product_id: 130,
    vendor_id: 4,
    product_name: 'Firm Ground Studded Football Shoes',
    description: 'Molded TPU cleats with textured synthetic upper for superior traction and ball control.',
    price: 2999.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.7,
    review_count: 110,
    brand: 'Sports Zone',
    imageUrl: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=800&auto=format&fit=crop&q=80',
    stock: 25,
  },
  {
    product_id: 131,
    vendor_id: 33,
    product_name: 'Composite Leather Indoor/Outdoor Basketball',
    description: 'Official Size 7 regulation basketball with deep channel design for maximum grip and handling.',
    price: 1299.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.6,
    review_count: 130,
    brand: 'Sports House',
    imageUrl: 'https://images.unsplash.com/photo-1519766304817-4f37bda74a29?w=800&auto=format&fit=crop&q=80',
    stock: 40,
  },
  {
    product_id: 132,
    vendor_id: 4,
    product_name: 'High-Modulus Graphite Tennis Racket',
    description: '300g isometric head tennis racket strung with durable synthetic gut for speed and control.',
    price: 4999.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.8,
    review_count: 85,
    brand: 'Sports Zone',
    imageUrl: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800&auto=format&fit=crop&q=80',
    stock: 15,
  },
  {
    product_id: 133,
    vendor_id: 33,
    product_name: 'Tournament Grade Carbon Fiber Badminton Racket',
    description: '82g ultra-lightweight high-tension frame strung at 28 lbs with aero-dynamic slim shaft.',
    price: 2799.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.9,
    review_count: 220,
    brand: 'Sports House',
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&auto=format&fit=crop&q=80',
    stock: 35,
  },
  {
    product_id: 134,
    vendor_id: 4,
    product_name: 'Duck Feather Badminton Shuttlecocks (Tube of 12)',
    description: 'Precision sorted goose/duck feather shuttles with solid cork base for consistent flight speed.',
    price: 899.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.7,
    review_count: 175,
    brand: 'Sports Zone',
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&auto=format&fit=crop&q=80',
    stock: 80,
  },
  {
    product_id: 135,
    vendor_id: 33,
    product_name: 'Competition Rubber Table Tennis Bat',
    description: '5-ply natural wood blade with ITTF-approved spin rubber and ergonomic flared handle.',
    price: 1199.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.6,
    review_count: 95,
    brand: 'Sports House',
    imageUrl: 'https://images.unsplash.com/photo-1534158914592-062992fbe900?w=800&auto=format&fit=crop&q=80',
    stock: 45,
  },
  {
    product_id: 136,
    vendor_id: 25,
    product_name: 'Ventilated Wrist-Wrap Gym Workout Gloves',
    description: 'Padded leather palm weightlifting gloves with integrated 18-inch elastic wrist stabilization wrap.',
    price: 699.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.8,
    review_count: 260,
    brand: 'Fitness World',
    imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    stock: 90,
  },
  {
    product_id: 137,
    vendor_id: 25,
    product_name: '8mm High-Density Non-Slip Yoga Mat',
    description: 'Eco-friendly TPE dual-textured fitness mat with alignment markings and carrying strap.',
    price: 1199.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.7,
    review_count: 310,
    brand: 'Fitness World',
    imageUrl: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&auto=format&fit=crop&q=80',
    stock: 70,
  },
  {
    product_id: 138,
    vendor_id: 25,
    product_name: '5-Level Heavy Duty Resistance Bands Set',
    description: '100% natural latex loop bands from X-Light to X-Heavy for stretching and physical therapy.',
    price: 799.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.6,
    review_count: 180,
    brand: 'Fitness World',
    imageUrl: 'https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?w=800&auto=format&fit=crop&q=80',
    stock: 85,
  },
  {
    product_id: 139,
    vendor_id: 25,
    product_name: 'Hex Rubber Encased Dumbbells (Pair of 10kg)',
    description: 'Cast iron solid core weights coated in heavy-duty rubber to prevent floor damage and rolling.',
    price: 3499.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.9,
    review_count: 140,
    brand: 'Fitness World',
    imageUrl: 'https://images.unsplash.com/photo-1586401100295-7a8096fd231a?w=800&auto=format&fit=crop&q=80',
    stock: 20,
  },
  {
    product_id: 140,
    vendor_id: 25,
    product_name: 'Cast Iron Solid Kettlebell (12kg)',
    description: 'Powder-coated textured finish kettlebell with wide flat base for crossfit swings and squats.',
    price: 2199.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.8,
    review_count: 95,
    brand: 'Fitness World',
    imageUrl: 'https://images.unsplash.com/photo-1586401100295-7a8096fd231a?w=800&auto=format&fit=crop&q=80',
    stock: 25,
  },
  {
    product_id: 141,
    vendor_id: 25,
    product_name: 'High-Speed Ball Bearing Skipping Rope',
    description: 'Tangle-free 360-degree rotating steel wire rope with adjustable length and non-slip aluminum grips.',
    price: 499.00,
    category: 'Sports',
    product_status: 'Active',
    rating: 4.5,
    review_count: 210,
    brand: 'Fitness World',
    imageUrl: 'https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?w=800&auto=format&fit=crop&q=80',
    stock: 110,
  },

  // --- BOOKS & LEARNING (23 products: 142 to 164) ---
  {
    product_id: 142,
    vendor_id: 10,
    product_name: 'Core Java: An Integrated Approach',
    description: 'Comprehensive guide covering OOP principles, JVM internals, multithreading, and collections framework.',
    price: 799.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.8,
    review_count: 220,
    brand: 'Book Store',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    stock: 50,
  },
  {
    product_id: 143,
    vendor_id: 28,
    product_name: 'Python Crash Course for Data Science',
    description: 'Hands-on project-based introduction to Python syntax, NumPy, pandas, and data visualization.',
    price: 849.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.9,
    review_count: 310,
    brand: 'Book World',
    imageUrl: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&auto=format&fit=crop&q=80',
    stock: 65,
  },
  {
    product_id: 144,
    vendor_id: 10,
    product_name: 'JavaScript: The Definitive Comprehensive Guide',
    description: 'Master ECMAScript 6+, asynchronous promises, event loop mechanics, and modern web APIs.',
    price: 999.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.7,
    review_count: 180,
    brand: 'Book Store',
    imageUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800&auto=format&fit=crop&q=80',
    stock: 40,
  },
  {
    product_id: 145,
    vendor_id: 28,
    product_name: 'Modern Full-Stack React Development',
    description: 'Deep dive into React 19, custom hooks, Tailwind CSS, TypeScript, and server components.',
    price: 899.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.8,
    review_count: 145,
    brand: 'Book World',
    imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&auto=format&fit=crop&q=80',
    stock: 45,
  },
  {
    product_id: 146,
    vendor_id: 10,
    product_name: 'Data Structures and Algorithms in Practice',
    description: 'Essential curriculum covering binary trees, graph algorithms, dynamic programming, and complexity.',
    price: 749.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.9,
    review_count: 340,
    brand: 'Book Store',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    stock: 80,
  },
  {
    product_id: 147,
    vendor_id: 28,
    product_name: 'Fundamentals of Database Systems',
    description: 'Standard textbook explaining relational algebra, SQL optimization, indexing, and ACID transactions.',
    price: 899.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.8,
    review_count: 190,
    brand: 'Book World',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80',
    stock: 55,
  },
  {
    product_id: 148,
    vendor_id: 10,
    product_name: 'Operating System Concepts (Silberschatz)',
    description: 'Authoritative resource on process synchronization, virtual memory, scheduling, and file systems.',
    price: 849.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.7,
    review_count: 215,
    brand: 'Book Store',
    imageUrl: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&auto=format&fit=crop&q=80',
    stock: 60,
  },
  {
    product_id: 149,
    vendor_id: 28,
    product_name: 'Computer Networking: A Top-Down Approach',
    description: 'Classic textbook on TCP/IP protocol suite, network security, DNS architecture, and routing algorithms.',
    price: 920.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.8,
    review_count: 175,
    brand: 'Book World',
    imageUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800&auto=format&fit=crop&q=80',
    stock: 40,
  },
  {
    product_id: 150,
    vendor_id: 28,
    product_name: 'Hands-On Machine Learning with Scikit-Learn',
    description: 'Practical guide to building end-to-end ML pipelines, regression, classification, and neural nets.',
    price: 1299.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.9,
    review_count: 260,
    brand: 'Book World',
    imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&auto=format&fit=crop&q=80',
    stock: 35,
  },
  {
    product_id: 151,
    vendor_id: 10,
    product_name: 'Deep Learning Foundations and Practice',
    description: 'Comprehensive coverage of deep neural networks, CNNs, transformers, and backpropagation mathematics.',
    price: 1499.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.8,
    review_count: 140,
    brand: 'Book Store',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    stock: 25,
  },
  {
    product_id: 152,
    vendor_id: 10,
    product_name: 'Computer System Architecture (Mano)',
    description: 'Detailed analysis of CPU registers, ALU micro-operations, pipelining, and memory hierarchy.',
    price: 699.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.7,
    review_count: 195,
    brand: 'Book Store',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80',
    stock: 70,
  },
  {
    product_id: 153,
    vendor_id: 28,
    product_name: "Software Engineering: A Practitioner's Approach",
    description: 'Architectural blueprints, agile development methodologies, software testing, and metrics.',
    price: 849.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.6,
    review_count: 160,
    brand: 'Book World',
    imageUrl: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&auto=format&fit=crop&q=80',
    stock: 45,
  },
  {
    product_id: 154,
    vendor_id: 28,
    product_name: 'Cloud Native Architecture & Microservices',
    description: 'Production patterns for container orchestration, API gateways, event-driven design, and resilience.',
    price: 1099.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.9,
    review_count: 130,
    brand: 'Book World',
    imageUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800&auto=format&fit=crop&q=80',
    stock: 30,
  },
  {
    product_id: 155,
    vendor_id: 10,
    product_name: 'Cyber Security Essentials & Network Defense',
    description: 'Practical guide covering threat modeling, penetration testing, cryptography, and zero trust security.',
    price: 949.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.7,
    review_count: 110,
    brand: 'Book Store',
    imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&auto=format&fit=crop&q=80',
    stock: 35,
  },
  {
    product_id: 156,
    vendor_id: 28,
    product_name: 'Clean Code: Agile Software Craftsmanship',
    description: 'Timeless handbook on writing readable, testable, maintainable, and robust enterprise code.',
    price: 899.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.9,
    review_count: 420,
    brand: 'Book World',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    stock: 90,
  },
  {
    product_id: 157,
    vendor_id: 10,
    product_name: 'System Design Interview Blueprint Guide',
    description: 'Step-by-step framework for designing scalable distributed systems, caching, and database sharding.',
    price: 1199.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.9,
    review_count: 380,
    brand: 'Book Store',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80',
    stock: 60,
  },
  {
    product_id: 158,
    vendor_id: 10,
    product_name: 'Atomic Habits: Proven Way to Build Good Habits',
    description: 'Global bestseller on transforming your life through small daily improvements and behavioral psychology.',
    price: 499.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.9,
    review_count: 550,
    brand: 'Book Store',
    imageUrl: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&auto=format&fit=crop&q=80',
    stock: 120,
  },
  {
    product_id: 159,
    vendor_id: 28,
    product_name: 'The Psychology of Money',
    description: 'Timeless lessons on wealth, greed, and happiness exploring behavioral biases in personal finance.',
    price: 450.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.9,
    review_count: 480,
    brand: 'Book World',
    imageUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800&auto=format&fit=crop&q=80',
    stock: 100,
  },
  {
    product_id: 160,
    vendor_id: 10,
    product_name: 'Deep Work: Rules for Focused Success',
    description: 'Essential guide to cultivating intense focus and eliminating cognitive distractions in modern work.',
    price: 499.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.8,
    review_count: 270,
    brand: 'Book Store',
    imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&auto=format&fit=crop&q=80',
    stock: 80,
  },
  {
    product_id: 161,
    vendor_id: 28,
    product_name: 'Zero to One: Notes on Startups',
    description: "Peter Thiel's provocative philosophies on building monopolistic technological innovation from scratch.",
    price: 550.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.8,
    review_count: 310,
    brand: 'Book World',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    stock: 75,
  },
  {
    product_id: 162,
    vendor_id: 10,
    product_name: 'Thinking, Fast and Slow',
    description: "Nobel laureate Daniel Kahneman's seminal exploration of dual-system human cognition and heuristics.",
    price: 599.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.7,
    review_count: 290,
    brand: 'Book Store',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80',
    stock: 65,
  },
  {
    product_id: 163,
    vendor_id: 28,
    product_name: 'The Lean Startup: Innovation Drive',
    description: "Eric Ries's foundational methodology on rapid prototyping, validated learning, and agile pivots.",
    price: 649.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.7,
    review_count: 240,
    brand: 'Book World',
    imageUrl: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&auto=format&fit=crop&q=80',
    stock: 50,
  },
  {
    product_id: 164,
    vendor_id: 28,
    product_name: 'Sapiens: A Brief History of Humankind',
    description: "Yuval Noah Harari's groundbreaking narrative tracing human cognitive evolution from foraging to AI.",
    price: 499.00,
    category: 'Books',
    product_status: 'Active',
    rating: 4.9,
    review_count: 620,
    brand: 'Book World',
    imageUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800&auto=format&fit=crop&q=80',
    stock: 140,
  }
];

// Helper to execute updating seedData, productImages, and SQL
function run() {
  console.log(`Generated ${newProducts.length} new products (Total catalog size: ${50 + newProducts.length})`);
  
  // Counts by category:
  const counts = { Electronics: 10, Fashion: 10, Home: 10, Sports: 10, Books: 10 };
  for (const p of newProducts) {
    counts[p.category] = (counts[p.category] || 0) + 1;
  }
  console.log('Category distribution:', counts);
}

run();
